config/routes.rb
Wine::Application.routes.draw do

  resources :reviewers
  resources :reviews
  match '/reviews/:reviewer_id/:subject_id' => 'reviews#edit', :as => :edit_review
  root :to => 'reviewers#welcome'

end

app/models/description.rb
class Description < ActiveRecord::Base
  has_many :reviews, through: :description_review

  default_scope order: :description

  attr_accessible :description
end

app/models/description_review.rb
class DescriptionReview < ActiveRecord::Base
  set_table_name 'descriptions_reviews'

  set_primary_key [:description_id, :review_id]

  belongs_to :description
  belongs_to :review
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to  :subject
  belongs_to  :reviewer
  has_many    :review_varietals
  has_many    :description_reviews
  has_many    :varietals,     through: :review_varietals
  has_many    :descriptions,  through: :description_reviews

  attr_accessible :subject_id, :reviewer_id, :rating, :price

  order :subject_id

  def self.find_or_new subject_id, reviewer_id
    result = self.find_by_subject_id_and_reviewer_id subject_id, reviewer_id
    result || self.new(subject_id: subject_id, reviewer_id: reviewer_id)
  end

  def descriptions_str
    self.descriptions.map(&:description) * '; '
  end

  def varietals_str
    self.varietals.map(&:varietal) * '; '
  end
end

app/models/review_varietal.rb
class ReviewVarietal < ActiveRecord::Base
  set_table_name 'reviews_varietals'

  self.primary_key = [:review_id, :varietal_id]

  belongs_to :review
  belongs_to :varietal
end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
  has_many :reviews
  has_many :subjects, through: :reviews

  attr_accessible :name, :email, :phone

  def missing_reviews
    missing_ids = (1..Subject.num).to_a - self.reviews.map{|x| x.subject_id}
    missing_ids.map{|x| Review.new subject_id: x, reviewer_id: self.id}
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :reviews
  has_many :reviewers, through: :reviews

  def self.num
    18
  end
end

app/models/varietal.rb
class Varietal < ActiveRecord::Base
  has_many  :review_varietals
  has_many  :reviews, through: :review_varietals

  default_scope order: :varietal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reviewers_controller.rb
class ReviewersController < ApplicationController
  def welcome
    @title = "Welcome to the wine party"
    @reviewers = Reviewer.all
    @new_reviewer = Reviewer.new
  end

  def create
    r = Reviewer.create params['reviewer']
    redirect_to r
  end

  def show
    @reviewer = Reviewer.find params[:id]
    @reviews = @reviewer.reviews

    @missing_reviews = @reviewer.missing_reviews
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def edit
    @reviewer         = Reviewer.find params[:reviewer_id]
    @review           = Review.find_or_new params[:subject_id], params[:reviewer_id]
    @description_ids  = @review.description_reviews.map &:description_id
    @all_descriptions = Description.all
    @varietal_ids     = @review.review_varietals.map &:varietal_id
    @all_varietals    = Varietal.all
  end

  def create
    r = Review.create params[:review]
    set_values r
  end

  def update
    r = Review.find params[:id]
    r.update_attributes params[:review]
    set_values r
  end

  def set_values r
    r.varietals     = (Varietal.find params[:varietal].keys rescue [])
    r.descriptions  = (Description.find params[:description].keys rescue [])
    r.save!
    redirect_to reviewer_path r.reviewer_id
  end

  def index

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/descriptions/_checkbox.erb
<span class="span2">
  <%= id = checkbox.id
      name = 'description[' + id.to_s + ']'
      checked = @description_ids.include? id
      check_box_tag name, 1, checked %>&nbsp;<%= label_tag name, checkbox.description %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag       "bootstrap.min", media: "all" %>
  <%= stylesheet_link_tag       "bootstrap-responsive.css", media: "all" %>
  <%# javascript_include_tag    "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row-fluid">
    <div class="span12">
      <h1><%= @title %></h1>
    </div>
  </div>
  <%= yield %>
</div>
</body>
</html>

app/views/reviewers/_new_reviewer.erb
<%= form_for @new_reviewer do |f| %>
  <span class="span3">
    <label for="name">Name</label>
    <%= f.text_field :name %>
  </span>
  <span class="span3">
    <label for="email">Email</label>
      <%= f.text_field :email %>
  </span>
  <span class="span3">
    <label for="phone">Phone</label>
    <%= f.text_field :phone %>
  </span>
    <span class="span1">
      <br />
      <button class="btn" id="newReviewer">New</button>
    </span>
<%- end %>

app/views/reviewers/_reviewer.erb
<span class="span-3 btn">
  <%= link_to reviewer.name, reviewer_path(reviewer) %>
</span>

app/views/reviewers/show.erb
<div class="row-fluid">
  <span class="span12"><h1><a href="/" class="btn btn-small pull-right"><i class="icon-home"></i></a><%= @reviewer.name %></h1></span>
</div>
<%-
@reviews.each do |r| -%>
    <%= render partial: '/reviews/show', locals: {reviews: r} %><%-
end %>
<hr><%-
@missing_reviews.each do |r| -%>
    <%= render partial: '/reviews/show', locals: {reviews: r} %><%-
end -%>

app/views/reviewers/welcome.erb
<%- if @reviewers.count > 0 -%>
    <div class="span12">
        Who are you?
    </div>
    <%= render @reviewers %>
    <div class="span12">
      … or are you new?
    </div>
    <%= render partial: 'new_reviewer' %>
<%- else -%>
    <div class="span12">
        New <strike>test subject</strike> reviewer!
    </div>
    <%= render partial: 'new_reviewer' %>
<%- end -%>

app/views/reviews/_show.erb
<%-
review = local_assigns[:reviews] -%>
<a href="<%= edit_review_path reviewer_id: review.reviewer_id, subject_id: review.subject_id %>">
<div class="row-fluid">
  <span class="span2">
    #<%= review.subject_id %>
  </span>
  <span class="span2">
    Rated: <%= review.rating %>/<%= number_to_currency review.price %>
  </span>
  <span class="span2">
    <%= review.descriptions_str.html_safe rescue '' %>
  </span>
  <span class="span2">
    <%= review.varietals_str.html_safe rescue '' %>
  </span>
</div>
</a>

app/views/reviews/edit.erb
<%=
form_for @review, html: {class: 'form-inline'} do |f| %><%=
    f.hidden_field 'reviewer_id', value: @review.reviewer_id %><%=
    f.hidden_field 'subject_id', value: @review.subject_id %>
    <div class="row-fluid">
      <h1>Wine #<%= @review.subject_id %> by <%= @reviewer.name %><a class="btn pull-right" href="<%= reviewer_path @review.reviewer_id %>"><i class="icon-list"></i></a></h1>
    </div>
<div class="row-fluid">
  <span class="span2">
    Rating (1&ndash;100): <%= f.text_field :rating, size: 3, type: 'number', min: 0, max:100, width: '2em', placeholder: 'Rating', class: 'input-mini' %>
  </span>
  <span class="span2">
    Price ($): <%= f.text_field :price, size: 3, type: 'number', min: 0, max:100, step: 'any', width: '2em', placeholder: 'Price', class: 'input-mini' %>
  </span>
</div>
<div class="row-fluid">
  <fieldset>
    <legend>Varietals</legend>
    <%= render partial: '/varietals/checkbox',      collection: @all_varietals,     locals: {selected: @selected_varietals} %>
  </fieldset>
  <fieldset>
    <legend>Descriptions</legend>
    <%= render partial: '/descriptions/checkbox',   collection: @all_descriptions,  locals: {selected: @selected_descriptions} %>
  </fieldset>
</div>
<div class="row-fluid">
  <button type="submit" class="btn">Submit</button>
</div>
<%-
end %>

app/views/varietals/_checkbox.erb
<span class="span3">
  <%= id = checkbox.id
      name = 'varietal[' + id.to_s + ']'
      checked = @varietal_ids.include? id
      check_box_tag name, 1, checked %>&nbsp;<%= label_tag name, checkbox.varietal %>
</span>